# Minimal yet useful baseline for CI
# - Use curated rule sets (requires network) / fallback to local rules if offline
rules:
  - id: forbidden-eval
    patterns:
      - pattern: eval(...)
    message: "Avoid eval(): security risk."
    severity: ERROR
    languages: [javascript, typescript]
  - id: fetch-http-url
    languages: [javascript, typescript, go, python]
    message: "Use HTTPS instead of HTTP for network calls."
    severity: WARNING
    pattern: |
      $CALL("http://"$X, ...)
  - id: hardcoded-credential
    languages: [generic]
    message: "Potential hardcoded secret/credential."
    severity: ERROR
    pattern-either:
      - pattern: /(?i)(api[_-]?key|secret|token|passwd|password)\s*[:=]\s*["'][A-Za-z0-9_\-]{12,}["']/
      - pattern: /(?i)re_[a-z0-9_]{20,}/   # Resend等のトークン風
