# STARLIST Semgrep configuration (extends p/ci ruleset)
# Used together with CLI-level directory exclusions in the Extended Security workflow.
# Placeholder rule ensures the configuration file remains valid while we iterate on per-rule tuning.
rules:
  - id: starlist-placeholder-noop
    languages: [generic]
    message: "Placeholder rule for repository-specific Semgrep configuration."
    severity: INFO
    patterns:
      - pattern: $X
      - metavariable-pattern:
          metavariable: $X
          pattern: "(?!)"  # impossible regex to avoid matches
