#!/usr/bin/env bash
# Linear APIを使用してIssueを作成するスクリプト
# 使用例: ./scripts/create-linear-issue.sh STA-8 "Production flow smoke test"

set -euo pipefail
IFS=$'\n\t'

usage() {
  cat <<'USAGE'
Usage: ./scripts/create-linear-issue.sh <ISSUE_KEY> "<TITLE>" [API_KEY]

ISSUE_KEY  : Linear の Issue キー（例: STA-8）。環境変数 LINEAR_ISSUE_KEY からも指定可。
TITLE      : Issue タイトル。LINEAR_ISSUE_TITLE を設定しておくと省略できます。
API_KEY    : 3番目の引数で API キーを渡すと LINEAR_API_KEY より優先されます。

Environments:
  LINEAR_API_KEY          : Linear Personal API key（必須）
  LINEAR_TEAM_ID          : 既存 Team の ID を指定するとチーム一覧の問い合わせを省略
  LINEAR_ISSUE_DESCRIPTION : {{ISSUE_KEY}} プレースホルダを含めて本文をカスタマイズ

LINEAR_ISSUE_DESCRIPTION 例: $'Issue {{ISSUE_KEY}} generated by CI\n- smoke test'

改行を含む場合は $'...' 形式を使用:
  export LINEAR_ISSUE_DESCRIPTION=$'{{ISSUE_KEY}}: title here\n- bullet point'

Use -h|--help to show this message again.
USAGE
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "❌ Error: '$1' が見つかりません。インストールしてください。" >&2
    exit 1
  fi
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

ISSUE_KEY="${1:-${LINEAR_ISSUE_KEY:-}}"
TITLE="${2:-${LINEAR_ISSUE_TITLE:-}}"
API_KEY="${3:-${LINEAR_API_KEY:-}}"

if [[ -z "$ISSUE_KEY" || -z "$TITLE" ]]; then
  echo "Usage: $0 <ISSUE_KEY> \"<TITLE>\" [API_KEY]"
  echo ""
  echo "例: ./scripts/create-linear-issue.sh STA-8 \"Production flow smoke test\""
  echo ""
  echo "API_KEYが指定されない場合、LINEAR_API_KEY環境変数を使用します。"
  echo "DESCRIPTIONはLINEAR_ISSUE_DESCRIPTIONで調整可能（{{ISSUE_KEY}}プレースホルダ対応）。"
  exit 1
fi

require_command "curl"
require_command "jq"

if [[ -z "$API_KEY" ]]; then
  echo "❌ Error: Linear APIキーが必要です。"
  echo ""
  echo "以下のいずれかの方法でAPIキーを設定してください："
  echo "1. 環境変数: export LINEAR_API_KEY='your-api-key'"
  echo "2. 引数として渡す: $0 $ISSUE_KEY \"$TITLE\" 'your-api-key'"
  echo ""
  echo "Linear APIキーの取得方法:"
  echo "1. Linearにログイン"
  echo "2. Settings > API > Personal API keys"
  echo "3. 新しいキーを生成"
  exit 1
fi

DESCRIPTION_TEMPLATE="${LINEAR_ISSUE_DESCRIPTION:-Created via Linear API automation for {{ISSUE_KEY}}}"
DESCRIPTION="${DESCRIPTION_TEMPLATE//\{\{ISSUE_KEY\}\}/${ISSUE_KEY}}"

TEAM_KEY="${ISSUE_KEY%%-*}"
if [[ -z "$TEAM_KEY" ]]; then
  TEAM_KEY="$ISSUE_KEY"
fi

LINEAR_TEAM_ID="${LINEAR_TEAM_ID:-}"
if [[ -n "$LINEAR_TEAM_ID" ]]; then
  TEAM_ID="$LINEAR_TEAM_ID"
  echo "ℹ️ LINEAR_TEAM_ID 環境変数を利用します。チーム一覧問い合わせはスキップされます。"
else
  echo "🔍 チーム情報を取得中..."
  TEAMS_PAYLOAD=$(jq -n --arg query 'query { teams { nodes { id name key } } }' '{ query: $query }')
  set +e
  TEAMS_RESPONSE=$(curl --fail-with-body -sS -X POST https://api.linear.app/graphql \
    -H "Content-Type: application/json" \
    -H "Authorization: ${API_KEY}" \
    -d "$TEAMS_PAYLOAD")
  TEAMS_EXIT=$?
  set -e
  if [[ $TEAMS_EXIT -ne 0 ]]; then
    echo "❌ Error: チーム情報の取得に失敗しました。HTTPステータスコード $TEAMS_EXIT"
    echo "Response: $TEAMS_RESPONSE"
    exit 1
  fi

  echo "$TEAMS_RESPONSE" | jq -r '.data.teams.nodes[] | "\(.key): \(.name) (ID: \(.id))"' || {
    echo "❌ Error: チーム情報のパースに失敗しました。"
    echo "Response: $TEAMS_RESPONSE"
    exit 1
  }

  TEAM_ID=$(echo "$TEAMS_RESPONSE" | jq -r ".data.teams.nodes[] | select(.key == \"${TEAM_KEY}\") | .id")
fi

if [[ -z "${TEAM_ID:-}" ]]; then
  echo "❌ Error: チーム '${TEAM_KEY}' が見つかりません。"
  exit 1
fi

echo ""
echo "📝 Issue作成中: ${ISSUE_KEY} - ${TITLE}"
echo "✅ チームID: ${TEAM_ID}"

QUERY='mutation ($input: IssueCreateInput!) { issueCreate(input: $input) { success issue { id identifier title url } } }'
REQUEST_PAYLOAD=$(jq -n \
  --arg query "$QUERY" \
  --arg team "$TEAM_ID" \
  --arg title "$TITLE" \
  --arg description "$DESCRIPTION" \
  '{ query: $query, variables: { input: { teamId: $team, title: $title, description: $description } } }')

set +e
CREATE_RESPONSE=$(curl --fail-with-body -sS -X POST https://api.linear.app/graphql \
  -H "Content-Type: application/json" \
  -H "Authorization: ${API_KEY}" \
  -d "$REQUEST_PAYLOAD")
CREATE_EXIT=$?
set -e

if [[ $CREATE_EXIT -ne 0 ]]; then
  echo "❌ Error: Issue作成リクエストが失敗しました（HTTPステータスコード $CREATE_EXIT）。"
  echo "Response: $CREATE_RESPONSE"
  exit 1
fi

# GraphQLエラーの詳細表示
ERROR_MESSAGES=$(echo "$CREATE_RESPONSE" | jq -r '.errors[]?.message // empty' 2>/dev/null || true)
if [[ -n "$ERROR_MESSAGES" ]]; then
  echo "❌ Linear API error(s):" >&2
  echo "$ERROR_MESSAGES" >&2
  # エラー詳細をログに保存
  echo "$CREATE_RESPONSE" | jq . > "out/linear_error_$(date +%Y%m%d_%H%M%S).json" 2>/dev/null || true
  exit 1
fi

SUCCESS=$(echo "$CREATE_RESPONSE" | jq -r '.data.issueCreate.success // false')
ISSUE_ID=$(echo "$CREATE_RESPONSE" | jq -r '.data.issueCreate.issue.identifier // empty')
ISSUE_URL=$(echo "$CREATE_RESPONSE" | jq -r '.data.issueCreate.issue.url // empty')

if [[ "$SUCCESS" == "true" && -n "$ISSUE_ID" ]]; then
  # 成功時の1行トースト（SOT貼り付け用）
  echo "✅ Linear: created ${ISSUE_ID} ${ISSUE_URL}"
  # レスポンスをログに保存
  mkdir -p "out/linear/$(date +%Y-%m-%d)"
  echo "$CREATE_RESPONSE" | jq . > "out/linear/$(date +%Y-%m-%d)/create_response_${ISSUE_ID}.json" 2>/dev/null || true
else
  echo "❌ Error: Issue作成に失敗しました。" >&2
  echo "Response: $CREATE_RESPONSE" >&2
  exit 1
fi
